Switch to integrated buildpack

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -36,29 +36,88 @@ else
   echo "       $CACHE_DIR/.geoip/libmaxminddb already cached"
 fi
 
+if [ ! -f "$ENV_DIR/MAXMIND_KEY" ]; then
+  echo "-----> You must define the environment variable MAXMIND_KEY with your license key."
+
+  exit 1
+fi
+MAXMIND_KEY=`cat $ENV_DIR/MAXMIND_KEY`
+MAXMIND_EDITIONS=`cat $ENV_DIR/MAXMIND_EDITIONS`
+
 # Copy libmaxminddb files to build dir
 cp -R $CACHE_DIR/.geoip/libmaxminddb $BUILD_DIR/vendor
 
-GEOLITECITY_URL="http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz"
-GEOLITECITY_FILE="GeoLite2-City.mmdb"
 
 echo "-----> Installing City Database"
+# Copy libmaxminddb files to build dir
+cp -R $CACHE_DIR/.geoip/libmaxminddb $BUILD_DIR/$VENDORED_GEOIP
 
-if [ ! -f $CACHE_DIR/.geoip/$GEOLITECITY_FILE ]; then
-  echo "       Downloading  $GEOLITECITY_FILE"
+if [ ! -f "$ENV_DIR/MAXMIND_KEY" ]; then
+  echo "-----> You must define the environment variable MAXMIND_KEY with your license key."
 
-  cd "$CACHE_DIR/.geoip"
-
-  curl -s -L -o ${GEOLITECITY_FILE}.gz $GEOLITECITY_URL
-  gunzip ${GEOLITECITY_FILE}.gz > /dev/null
-
-  cd $HOME
-else
-  echo "       $GEOLITECITY_FILE already cached"
+  exit 1
 fi
 
-cp "$CACHE_DIR/.geoip/$GEOLITECITY_FILE" "$BUILD_DIR/vendor/share/$GEOLITECITY_FILE"
-GEOIP_DB_PATH="\$HOME/vendor/share/$GEOLITECITY_FILE"
+mkdir -p $CACHE_DIR
+
+download(){
+  EDITION=$1
+
+  TAR="$CACHE_DIR/$EDITION.tar.gz"
+  DB="$CACHE_DIR/$EDITION.mmdb"
+  LAST="$CACHE_DIR/$EDITION.last"
+
+  if [ -f $DB ]; then
+    if [ -f $LAST ]; then
+      touch -d '-1 week' limit
+
+      if [ limit -nt $LAST ]; then
+        echo "-----> $EDITION: Database is older than a week, clearing cache."
+
+        rm $DB
+      fi
+    else
+      echo "-----> $EDITION: Unable to determine last download time, clearing cache."
+
+      rm $DB
+    fi
+  fi
+
+  if [ ! -f $DB ]; then
+    if [ ! -f $TAR ]; then
+      echo "-----> $EDITION: Database does not exist in cache, downloading."
+
+      curl -o $TAR -L "https://download.maxmind.com/app/geoip_download?edition_id=${EDITION}&suffix=tar.gz&license_key=$MAXMIND_KEY"
+    fi
+
+    echo "-----> $EDITION: Extracting $TAR"
+
+    tar -zxvf $TAR -C $CACHE_DIR --no-anchored --strip-components=1 "$EDITION.mmdb"
+
+    touch $LAST
+  else
+    echo "-----> $EDITION: Database already exists in cache."
+  fi
+
+  OUTPUT="$BUILD_DIR/$SAVE"
+
+  echo "-----> $EDITION: Copying $DB to $OUTPUT"
+
+  cp $DB $OUTPUT
+
+  if [ -f $TAR ]; then
+    rm $TAR
+  fi
+}
+
+IFS=', ' read -a editions <<< "$MAXMIND_EDITIONS"
+
+for edition in "${editions[@]}"
+do
+    download "$edition"
+done
+
+GEOIP_DB_PATH="\$HOME/vendor/share/GeoIP2-City.mmdb"
 
 PROFILE_PATH="$BUILD_DIR/.profile.d/libmaxminddb.sh"
 mkdir -p $(dirname $PROFILE_PATH)
